# -*- coding: utf-8 -*-
"""Klasifikasi Naive Beyes Kelompok 5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Drvgu8zczXzYcBT91OMyPwYA9Qyf-iDo
"""

from IPython import get_ipython
from IPython.display import display
import numpy as np
import pandas as pd

from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score

dataset = pd.read_csv('Proporsi_Korban_Kejahatan_Indonesia_2021.csv')
dataset.head()

dataset.info()

dataset.empty

en = LabelEncoder()
dataset ['Proporsi_Korban_Kejahatan_Persen']= en.fit_transform(dataset['Proporsi_Korban_Kejahatan_Persen'])
dataset.head()

x = dataset.iloc[:, -1:].values
y = dataset.iloc[:, 1].values

y_discretized = pd.cut(y, bins=4, labels=[0, 1, 2, 3])



x

y

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=0)

print("x_train = ", len(x_train))
print("x_test = ", len(x_test))
print("y_train = ", len(y_train))
print("y_test = ", len(y_test))

sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

x_train

x_test

y_train

y_test

classifier = GaussianNB()
classifier.fit(x_train, y_train)

y_pred = classifier.predict(x_test)
y_pred

classifier.predict_proba(x_test)

cm = confusion_matrix(y_test, y_pred)
print(cm)

akurasi = classification_report(y_test, y_pred)
print(akurasi)

akurasi = accuracy_score(y_test, y_pred)
print("tingkat akurasi : %d" % (akurasi*100))

ydata = pd.DataFrame()
ydata['y_test'] = pd.DataFrame (y_test)
ydata['y_pred'] = pd.DataFrame (y_pred)
ydata

ydata.to_excel('dataactualpred.xlsx', index=False)